# -*- coding: utf-8 -*-
"""2137.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B1MEJX3jaz1p1F8Cab7UjRaIDwKMjkpF
"""

while True:
  try:
    n = int(input())
    bruh = []
    for i in range(n):
        bruh.append(int(input()))

    for i in range(n-1):
        for i in range(n-1):
            if(bruh[i] > bruh[i+1]):
                aux = bruh[i]
                bruh[i] = bruh[i+1]
                bruh[i+1] = aux

    for i in range(n):
        while(len(str(bruh[i]))!=4): 
            bruh[i] = '0' + str(bruh[i])
        print(bruh[i])
  except EOFError:
    break